[unstable]
build-std = ["panic_abort", "std"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-cpu=mvp", "-C", "target-feature=+mutable-globals,+sign-ext,+bulk-memory,+nontrapping-fptoint"]
